name: swift_slots
description: Swift Slots - Discover and book discounted last-minute appointments nearby.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.1
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_local_notifications: ^17.1.2
  cached_network_image: ^3.3.1
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  uuid: ^4.4.0
  collection: ^1.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/copy/
    - assets/images/

dev_dependencies:
  flutter_lints: ^3.0.1

